---
apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
  labels:
    name: test-ns
---
apiVersion: v1
kind: Service
metadata:
  name: tms-exam-service
spec:
  selector:
    project: tms-exam
  type: NodePort
  ports:
    - name : http
      port: {{ .Values.Port }}
      nodePort: {{ .Values.NodePort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms-exam-deployment
  labels:
    app: tms-exam-app
spec:
  replicas: {{ .Values.ReplicaCount }}
  selector: 
    matchLabels:
      project: tms-exam
  template:
    metadata:
      labels:
        project: tms-exam
    spec:
      containers:
        - name: tms-exam-web
          image: {{ .Values.image.repository }}: {{ .Values.image.tag | default .Chart.AppVersion }}
          ports: 
            - containerPort: 80
