---
apiVersion: v1
kind: Namespace
metadata:
  name: test-ns
  labels:
    name: test-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.ReplicaCount }}
  selector: 
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-web
          image: {{ .Values.image.repository }}: {{ .Values.image.tag | default .Chart.AppVersion }}
          ports: 
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tms-exam-service
spec:
  selector:
    project: {{ .Release.Name }}
  type: NodePort
  ports:
    - name : http
      port: {{ .Values.Port }}
      nodePort: {{ .Values.NodePort }}
