apiVersion: v1
kind: Service
metadata:
  name: tms-exam-service
spec:
  selector:
    project: {{ .Release.Name }}
  type: NodePort
  ports:
    - name : http
      port: {{ .Values.Port }}
      nodePort: {{ .Values.NodePort }}
